#!/bin/bash

if [ $# -eq 0 ]
then
	echo "No arguments supplied, you should provide the target environment (which should match a profile you have in your maven settings.xml)"
	AVAILABLE_ENVS=$(grep -oP "(?<=<value>)[^<]+" $M2_HOME/conf/settings.xml|tr '\n' ',')
	echo "Available environments are: ${AVAILABLE_ENVS}"
	echo "example: deploy.sh int"
	exit 1
fi

TARGET_ENV=$1
shift

AVAILABLE_ENVS=$(grep -oP "(?<=<value>)[^<]+" $M2_HOME/conf/settings.xml|tr '\n' ',')
if ! grep -q $TARGET_ENV <<<$AVAILABLE_ENVS;
then
	echo "Available environments are: ${AVAILABLE_ENVS}"
	exit 1
fi

echo "Deploying to ${TARGET_ENV}"

if [ $TARGET_ENV != "local" ]
then
	echo "Stopping Weblogic"
	mvn -f wl-stop-pom.xml weblogic:wlst -Denv=$TARGET_ENV $*
fi

echo "UnDeploying application"
mvn -f wl-undeploy-pom.xml weblogic:wlst -Denv=$TARGET_ENV $*

echo "Deploying application"
mvn -pl eu.europa.ec.rdg.sygma:sygma-application weblogic:deploy -Denv=$TARGET_ENV $*
mvn -pl eu.europa.ec.rdg.sygma:sygma-it-plumber-ear weblogic:deploy -Denv=$TARGET_ENV $*

if [ $TARGET_ENV != "local" ]
then
	echo "Starting Weblogic"
	mvn -f wl-start-pom.xml weblogic:wlst -Denv=$TARGET_ENV $*
fi


