# Logs in RHEL are handled by daemon service : systemd-journal.service, and other associated services/sockets :

israel@W9980173 ~/git/iib-deploy/IIB-Deploy $ systemctl -a | grep journal																																			systemd-journal-flush.service                                                                                                                loaded    active   exited    Flush Journal to Persistent Storage
  systemd-journald.service                                                                                                                     loaded    active   running   Journal Service
  systemd-journald-audit.socket                                                                                                                loaded    active   running   Journal Audit Socket
  systemd-journald-dev-log.socket                                                                                                              loaded    active   running   Journal Socket (/dev/log)
  systemd-journald.socket                                                                                                                      loaded    active   running   Journal Socket

# Logs are then passed to service rsyslog for processing :

israel@W9980173 ~/git/iib-deploy/IIB-Deploy $ systemctl -a | grep rsyslog  rsyslog.service                                                     loaded    active   running   System Logging Service


### These logs are then written in : /var/log/

var/log/messages - all syslog messages except those mentioned below

var/log/secure - security and authentication-related messages and errors

var/log/maillog - mail server-related messages and errors

var/log/cron - log files related to periodically executed tasks

var/log/boot.log - log files related to system startup


# options to check logs :

tail -n 25 /var/log/messages

# to check live logs :

tail -f /var/log/secure


### Some logs are better to be checked using journalctl :

# Live logs for all services, not all, use -f :

journalctl -f

# specifying a service with -u :

journalctl -f -u apache

journalctl -f -u dbus

journalctl _SYSTEMD_UNIT=avahi-daemon.service


# Show all logs generated by the D-Bus executable:

journalctl /usr/bin/dbus-daemon

# complete example with dbus (dbus.service) :

W9980173 ~ # journalctl -f -u dbus
-- Logs begin at Fri 2018-12-14 11:31:02 CET. --
Dec 14 14:28:00 W9980173 dbus[1069]: [system] Activating via systemd: service name='org.freedesktop.hostname1' unit='dbus-org.freedesktop.hostname1.service'
Dec 14 14:28:00 W9980173 dbus[1069]: [system] Successfully activated service 'org.freedesktop.hostname1'
Dec 14 15:02:40 W9980173 dbus[1069]: [system] Activating via systemd: service name='org.freedesktop.ConsoleKit' unit='console-kit-daemon.service'
Dec 14 15:02:40 W9980173 dbus[1069]: [system] Successfully activated service 'org.freedesktop.ConsoleKit'
^C      
W9980173 ~ # journalctl _SYSTEMD_UNIT=dbus.service 
-- Logs begin at Fri 2018-12-14 11:31:02 CET, end at Fri 2018-12-14 15:03:58 CET. --
Dec 14 14:28:00 W9980173 dbus[1069]: [system] Activating via systemd: service name='o
Dec 14 14:28:00 W9980173 dbus[1069]: [system] Successfully activated service 'org.fre
Dec 14 15:02:40 W9980173 dbus[1069]: [system] Activating via systemd: service name='o
Dec 14 15:02:40 W9980173 dbus[1069]: [system] Successfully activated service 'org.fre

W9980173 ~ # journalctl /usr/bin/dbus-daemon 
-- Logs begin at Fri 2018-12-14 11:31:02 CET, end at Fri 2018-12-14 15:03:58 CET. --
Dec 14 14:28:00 W9980173 dbus[1069]: [system] Activating via systemd: service name='o
Dec 14 14:28:00 W9980173 dbus[1069]: [system] Successfully activated service 'org.fre
Dec 14 15:02:40 W9980173 dbus[1069]: [system] Activating via systemd: service name='o
Dec 14 15:02:40 W9980173 dbus[1069]: [system] Successfully activated service 'org.fre
lines 1-5/5 (END)


# Show all kernel logs from previous boot:
journalctl --list-boots
# if there is an ID boot 1:
journalctl -k -b -1

# other options:

W9980173 ~ # journalctl --
--after-cursor    --flush           --local           --reverse         --update-catalog
--all             --follow          --machine         --root            --user
--boot            --force           --merge           --rotate          --user-unit
--catalog         --full            --new-id128       --setup-keys      --utc
--cursor          --header          --no-full         --show-cursor     --vacuum-size
--directory       --help            --no-pager        --since           --vacuum-time
--disk-usage      --identifier      --no-tail         --sync            --verify
--dmesg           --interval        --output          --system          --verify-key
--dump-catalog    --lines           --pager-end       --this-boot       --version
--field           --list-boots      --priority        --unit            
--file            --list-catalog    --quiet           --until           

