# Logs in RHEL are handled by daemon service : systemd-journal.service, and other associated services/sockets :

israel@W9980173 ~/git/iib-deploy/IIB-Deploy $ systemctl -a | grep journal																																			systemd-journal-flush.service                                                                                                                loaded    active   exited    Flush Journal to Persistent Storage
  systemd-journald.service                                                                                                                     loaded    active   running   Journal Service
  systemd-journald-audit.socket                                                                                                                loaded    active   running   Journal Audit Socket
  systemd-journald-dev-log.socket                                                                                                              loaded    active   running   Journal Socket (/dev/log)
  systemd-journald.socket                                                                                                                      loaded    active   running   Journal Socket

# Logs are then passed to service rsyslog for processing :

israel@W9980173 ~/git/iib-deploy/IIB-Deploy $ systemctl -a | grep rsyslog  rsyslog.service                                                     loaded    active   running   System Logging Service


### These logs are then written in : /var/log/

var/log/messages - all syslog messages except those mentioned below

var/log/secure - security and authentication-related messages and errors

var/log/maillog - mail server-related messages and errors

var/log/cron - log files related to periodically executed tasks

var/log/boot.log - log files related to system startup


# options to check logs :

tail -n 25 /var/log/messages

# to check live logs :

tail -f /var/log/secure


### Some logs are better to be checked using journalctl :

# Live logs for all services, not all, use -f :

journalctl -f

# specifying a service with -u :

journalctl -f -u apache

journalctl -f -u dbus

journalctl _SYSTEMD_UNIT=avahi-daemon.service


# Show all logs generated by the D-Bus executable:

journalctl /usr/bin/dbus-daemon



# Show all kernel logs from previous boot:
journalctl --list-boots
# if there is an ID boot 1:
journalctl -k -b -1
