version: 1
formatters:
  warningFormat:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  errorFormat: 
    format: '%(asctime)s - Logger: %(name)s - pid: %(process)d - %(levelname)s - %(message)s: %(pathname)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
handlers:
  console:
    class: logging.StreamHandler
    level: WARNING
    formatter: warningFormat
    stream: ext://sys.stdout
  file:
    class : logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: errorFormat
    filename: logconfig.log
    maxBytes: 1024
    backupCount: 3
loggers:
  sampleLogger:
    handlers: [console, file]
root:
  level: WARNING
  handlers: [console, file]