package eu.europa.ec.rdg.eris.document.common;

public enum ErisClientErrorCode {

    ATTACHMENT_NAME_CANNOT_BE_EMPTY(30106),
    ATTACHMENT_NAME_CONTAINS_ILLEGAL_CHARACTERS(30107),
    DOCUMENT_REF_CANNOT_BE_EMPTY(30108),
    MASTER_ID_CANNOT_BE_EMPTY(30109),
    DOWNLOADDOCATTACHMENTTYPE_IS_INVALID(30110),
    INVALID_PARAMETERS(30111),

    ERROR_DOWNLOADING_ATTACHMENT(40109),
    ERROR_DOWNLOADING_ATTACHMENT_ZIP(40110),
    ERROR_UPLOADING_OR_DOWNLOADING_ATTACHMENT(40111),
    ERROR_COMPARING_ATTACHMENTS(40112),
    ERROR_UPLOADING_ATTACHMENT(40102),

    SECURITY_EXCEPTION(51116),
    ERROR_GENERATING_PROXY_TICKET(51117) ;

    private Integer code;

    private ErisClientErrorCode(Integer code){this.code = code;}

    public Integer getCode() {
        return code;
    }
}
